PREP/Models/ReleaseTabs.cs
using PREP.DAL.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace PREP.Models
{
    public class ReleaseTabs
    {
        public ReleaseGeneralDetails GeneralDetails { get; set; }
        public ReleaseAndFamilyProducts ProductsInScope { get; set; }
        public IEnumerable<ReleaseCharacteristicVM> ReleaseCharacteristic { get; set; }
        public IEnumerable<ReleaseCPReviewMode> CheckPointReviewMode { get; set; }
        public IEnumerable<ReleaseMilestoneVM> ReleaseMilestones { get; set; }
        public IEnumerable<ReleaseStakeholderVM> ReleaseStakeholders { get; set; }
        public IEnumerable<ReleaseAreaOwners> AreaOwners { get; set; }
        public Vendor VendorFocalPoints { get; set; }
    }


 
}

PREP/Controllers/ReleasesController.cs
using EntityFramework.BulkInsert.Extensions;
using PREP.DAL;
using PREP.DAL.Functions;
using PREP.DAL.Models;
using PREP.DAL.Repositories;
using PREP.DAL.Repositories.Memory;
using PREP.DAL.TableViews;
using PREP.Functions;
using PREP.Models;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Security.Principal;
using System.Text;
using System.Threading.Tasks;
using System.Transactions;
using System.Web;
using System.Web.Mvc;

namespace PREP.Controllers
{
  //  [Authorize(Roles = @"NTNET\ITPrepTest")]
    public class ReleasesController : BaseController
    {
        #region Private Properties
        public CurrentRelease CurrentRelease
        {
            get
            {
                if (!(Session["currentRelease"] is CurrentRelease))
                    return null;
                return (CurrentRelease)Session["currentRelease"];

            }
        }


        #endregion

        #region Private Methods
        /// <summary>
        /// reset Current Release And Mode ,Sets CurrentTabIndex to 0
        /// </summary>
        /// <param name="ReleaseId"></param>
        /// <param name="Mode">Add Edit or View </param>
        void SetCurrentRelease(int ReleaseId = 0, Mode Mode = Mode.ADD, int TabIndex = 0)
        {
            CurrentRelease currentRelease = new CurrentRelease();
            using (ReleaseRepository db = new ReleaseRepository())
            {
                currentRelease.ReleaseId = ReleaseId;
                currentRelease.Mode = Mode;
                if (Mode == Mode.ADD)
                {
                    currentRelease.Release = db.GetNewReleseAndRelationships();
                }
                else
                {
                    currentRelease.Release = db.GetReleseAndRelationships(currentRelease.ReleaseId);
                }
                Session["CurrentRelease"] = currentRelease;
                currentRelease.Tabs = new ReleaseTabs
                {
                    GeneralDetails = GetReleaseGeneralDetails(),
                    ProductsInScope = GetProductsInScope(),
                    ReleaseCharacteristic = GetReleaseCharacteristic(),
                    ReleaseMilestones = GetReleaseMilestoneVM(),
                    ReleaseStakeholders = GetReleaseStakeholder(),
                    AreaOwners = GetReleaseAreaOwners(),
                    CheckPointReviewMode = new List<ReleaseCPReviewMode>() { },
                };
                currentRelease.CurrentTabIndex = TabIndex;
            };
        }
        private bool IsExistCheckList(int releaseID)
        {
            using (IReleaseChecklistAnswerRepository db = new ReleaseChecklistAnswerRepository())
            {
                return db.IsExistCheckList(releaseID);
            }
        }
        /// <summary>
        /// find if ExistCheckList in Details.js beffore initiate
        /// </summary>
        public JsonResult ExistCheckListAnswers(int releaseID)
        {
            return Json(new { Result = IsExistCheckList(releaseID) });
        }
        #endregion

        #region Releselist
        // fill the view model-Releases

        public ActionResult AjaxHandler(jQueryDataTableParamModel param)
        {
            List<ReleaseView> Releases = new List<ReleaseView>();
            int CountRecord = 0;

            using (IReleaseRepository Db = new ReleaseRepository())
            {
                Releases = Db.GetByFiltering(param.iDisplayStart, param.iDisplayLength, param.SortBy, param.sSearch, out CountRecord).ToList();
            }


            return Json(new
            {
                sEcho = param.sEcho,
                iTotalRecords = CountRecord,
                iTotalDisplayRecords = CountRecord,
                aaData = Releases
            }, JsonRequestBehavior.AllowGet);

        }

        public async Task<ActionResult> Index(String textSearch = null)
        {
            ViewBag.textSearch = textSearch;
            return View();
        }
        #endregion

        #region Header
        public PartialViewResult _ReleaseHeader(int ReleaseID, ReleaseGeneralDetails GeneralDetails)
        {
            using (IReleaseChecklistAnswerRepository db = new ReleaseChecklistAnswerRepository())
            {
                ViewBag.IsExistCheckList = db.IsExistCheckList(ReleaseID);
            }
            return PartialView(GeneralDetails);
        }
        #endregion

        #region footer
        public PartialViewResult _ReleaseFooter(int releaseId)
        {
            Release releaseFooter;
            //if after Save
            if (CurrentRelease == null || CurrentRelease.ReleaseId != releaseId)
            {
                if (releaseId == 0)
                    return PartialView();
                else
                {
                    using (IReleaseRepository db = new ReleaseRepository())
                    {
                        releaseFooter = db.GetReleaseCPData(releaseId);
                    }
                }
            }
            else
            {
                releaseFooter = CurrentRelease.Release;
            }
            if (releaseFooter != null && releaseId != 0)
            {
                foreach (var rm in releaseFooter.ReleaseMilestones)
                {
                    ViewData[rm.Milestone.Name] = String.Format("{0:d-MMM-yyyy}", rm.MilestoneDate);
                }
                ReleaseCPView rcpview;
                foreach (var rcp in releaseFooter.ReleaseCPs)
                {
                    rcpview = new ReleaseCPView(rcp, releaseFooter.Account.Name);
                    ViewData[rcpview.CPName.Trim().Replace(" ", String.Empty)] = rcpview.PlannedDate != null ? "(" + String.Format("{0:d-MMM-yyyy}", rcpview.PlannedDate) + ")" : String.Empty;
                    ViewData[rcpview.CPName.Trim().Replace(" ", String.Empty) + "id"] = rcpview.ReleaseCPID;
                }
            }
            return PartialView();
        }

        public PartialViewResult releaseCPDetails(int CPID)
        {
            using (IReleaseCPRepository db = new ReleaseCPRepository())
            {
                var CPDetails = db.GetReleaseCPViewById(CPID);
                CPDetails.PublicationMailLink = CPDetails.PublicationMailLink != null ? ConfigurationManager.AppSettings["PublicationMailsFolder"] + CPDetails.PublicationMailLink : "#";
                return PartialView(CPDetails);
            }
        }
        [HttpGet]
        public PartialViewResult EditReleaseCPDetails(int releaseCP)
        {
            using (IReleaseCPRepository db = new ReleaseCPRepository())
            {
                return PartialView(db.GetReleaseCPViewById(releaseCP));
            }
        }

        [HttpPost]
        public async Task<int> SaveReleaseCPDetails(ReleaseCPView releaseCP)
        {
            int count = 0;
            using (IReleaseCPRepository db = new ReleaseCPRepository())
            {
                count += await db.Edit(releaseCP, (WindowsPrincipal)User);
            }
            return count;
        }

        #endregion

        #region Details



        #region Navigation Tabs
        private IEnumerable<ReleaseCharacteristicVM> GetReleaseCharacteristic()
        {
            return from tbl in CurrentRelease.Release.ReleaseCharacteristics
               .Where(a => a.Characteristic != null )
               .OrderBy(a => a.Characteristic.Order)
                   select
                   new ReleaseCharacteristicVM()
                   {
                       CharacteristicID=tbl.CharacteristicID,
                       CharacteristicName = tbl.Characteristic.Name != null ? tbl.Characteristic.Name: String.Empty,
                       ToolTip = tbl.Characteristic.ToolTip !=null? tbl.Characteristic.ToolTip: String.Empty,
                       IsChecked = tbl.IsChecked
                   };         
        }
        private ReleaseGeneralDetails GetReleaseGeneralDetails()
        {
            var CurrentGeneralDetails = new ReleaseGeneralDetails(CurrentRelease.Release);
            //{
            //    // IsFullTrack = (CurrentRelease.Release.ReleaseCPReviewModeQs.Count > 0 ? CurrentRelease.Release.ReleaseCPReviewModeQs.FirstOrDefault().IsFullTrack : false),
            //    //ReleaseID = CurrentRelease.ReleaseId != 0 ? CurrentRelease.Release.ReleaseID : new Nullable<Int32>(),
            //    //AccountID = CurrentRelease.Release.Account != null ? CurrentRelease.Release.Account.AccountID : 0,
            //    //AccountName = CurrentRelease.Release.Account != null ? CurrentRelease.Release.Account.Name : "",
            //    //Name = CurrentRelease.Release.Name,
            //    //Size = CurrentRelease.Release.Size,
            //    //LOB = CurrentRelease.Release.LOB,
            //    //LastCP = CurrentRelease.Release.ReleaseCPs.OrderByDescending(rcp => rcp.PublicationMailDate).First().CP.Name,
            //    //LastCPDate = CurrentRelease.Release.ReleaseCPs.OrderByDescending(rcp => rcp.PublicationMailDate).First().CP.Name
            //    //Accounts = new AccountRepository().Get(a => a.IsDeleted == false).ToList(),

            //    //DismissIndicator = CurrentRelease.Release.DismissIndicator

            //};
            using (IHistoryRepository db = new HistoryRepository())
            {
                var activityLogCreated = db.GetLastActivityLogUpdate(CurrentRelease.Release.ReleaseID, ActivityType.Create);
                if (activityLogCreated != null)
                {
                    CurrentGeneralDetails.CreatedDate = activityLogCreated.ActivityLog.Date;
                    CurrentGeneralDetails.CreatedBy = activityLogCreated.ActivityLog.Employee.FirstName + " " + activityLogCreated.ActivityLog.Employee.LastName;
                }
                var activityLogUpdated = db.GetLastActivityLogUpdate(CurrentRelease.Release.ReleaseID, null);

PREP/Views/Releases/EditReleaseCPDetails.cshtml
@model PREP.DAL.TableViews.ReleaseCPView
@*<script src="~/Scripts/ReleaseDetails.js"></script>*@
<script>
    $(document).ready(function () {
        $(".exit-popup-btn").click(exitPopUpWindow);
       // $("#cp-details-Edit").click(function () { ChangeContentPopUpWindow("/Releases/EditReleaseCPDetails", { releaseCP: $("#milstone-strip-wrapper").data("selectedmilstone") }); ; })
        // cp - details - cancel
        $("#cp-details-cancel").click(exitPopUpWindow);
        $("#cp-details-save").click(cpDetailsSave);
        setDatePicker();
    });
</script>
@using (Html.BeginForm("EditReleaseCPDetails", "Releases", FormMethod.Post, new { @class = "popUpViewWrapper" }))
{
    @Html.AntiForgeryToken()
    <input type="button" class="exit-popup-btn x-btn" value="X" />
    <h2 class="header-title">
        CP Details
    </h2>
    <div class="detailsContent detailsContentPopUp editPopUp">

        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        
            
                @Html.HiddenFor(model => model.ReleaseCPID)

       
        <div class="form-group">
            @Html.LabelFor(model => model.CPName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CPName, new { htmlAttributes = new { @class = "editItemreadonly", @readonly = "readonly" } })
            </div>
        </div>
        <hr />
        <div class="form-group">
            @Html.LabelFor(model => model.ReleaseID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ReleaseID, new { htmlAttributes = new { @class = "editItemreadonly", @readonly = "readonly" } })
            </div>
        </div>
        <hr />
        <div class="form-group">
            @Html.LabelFor(model => model.ReleaseName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ReleaseName, new { htmlAttributes = new { @class = "editItemreadonly", @readonly = "readonly" } })
            </div>
        </div>
        <hr />
        <div class="form-group">
            @Html.LabelFor(model => model.AccountName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AccountName, new { htmlAttributes = new { @class = "editItemreadonly", @readonly = "readonly" } })
            </div>
        </div>
        <hr />
        <div class="form-group">
            @Html.LabelFor(model => model.PlannedDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.PlannedDate, "{0:dd-MMM-yyyy}", new { @class = "editItemreadonly", @readonly = "readonly" })
            </div>
        </div>
        <hr />
        <div class="form-group">
            @Html.LabelFor(model => model.PublicationMailDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PublicationMailDate, new { htmlAttributes = new { @class = "editItemreadonly", @readonly = "readonly" } })
                @Html.ValidationMessageFor(model => model.PublicationMailDate, "", new { @class = "text-danger" })
            </div>
        </div>
        <hr />
        <div class="form-group">
            @Html.LabelFor(model => model.PublicationMailLink, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @*@Html.EditorFor(model => model.PublicationMailLink, new { htmlAttributes = new { @class = "editItemreadonly", @readonly = "readonly" } })
                @Html.ValidationMessageFor(model => model.PublicationMailLink, "", new { @class = "text-danger" })*@
                @if (Model.PublicationMailLink == "#")
                {
                    <a title="No mail was sent" download>Download </a>
                }
                else
                {
                    <a href="@Model.PublicationMailLink" download>Download </a>
                }
            </div>
        </div>
        <hr />
        <div class="form-group">
            @Html.LabelFor(model => model.ExceptionIndicator, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.ExceptionIndicator)
                    @Html.ValidationMessageFor(model => model.ExceptionIndicator, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>
        <hr />
        <div class="form-group form_datetime">
            @Html.LabelFor(model => model.ExceptionDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ExceptionDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ExceptionDate, "", new { @class = "text-danger" })
            </div>
        </div>
        <hr />
        <div class="form-group">
            @Html.LabelFor(model => model.ExceptionRemarks, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.ExceptionRemarks, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ExceptionRemarks, "", new { @class = "text-danger" })
            </div>
        </div>
        <hr />
        <div class="form-group">
            @Html.LabelFor(model => model.DelayDays, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DelayDays, new { htmlAttributes = new { @class = "editItemreadonly", @readonly = "readonly" } })
            </div>
        </div>
        <hr />
        <div class="form-group">
            @Html.LabelFor(model => model.Comments, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.Comments, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Comments, "", new { @class = "text-danger" })
            </div>
        </div>
        <hr />
    </div>
    <div class="tabs-action-button">
        <input type="button" value="Save" class="footer-button" id="cp-details-save" />
        <input type="button" value="Cancel" class="footer-button" id="cp-details-cancel" />
    </div>
}

PREP/Views/Releases/_EditReleaseCPDetails.cshtml
@model PREP.DAL.Models.ReleaseCP
<script src="~/Scripts/CheckPointDetails.js"></script>

@using (Html.BeginForm("EditReleaseCPDetails", "Releases",FormMethod.Post,new {@class ="popUpForm"}))
{
    @Html.AntiForgeryToken()

   
        <h2 class="header-title">
            ReleaseCP
        </h2>
        <div class="detailsContent detailsContentPopUp">
            
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.ReleaseCPID)

            @Html.HiddenFor(model => model.ReleaseID)

            @Html.HiddenFor(model => model.PublicationID)

            <div class="form-group">
                <div class="item-lable">
                    @Html.LabelFor(model => model.CPID, htmlAttributes: new { @class = "control-label col-md-2" })
                </div> <div class="col-md-10">
                    @Html.EditorFor(model => model.CPID, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.CPID, "", new { @class = "text-danger" })
                </div>
            </div>
            <hr/>
          
            <div class="form-group">
                <div class="item-lable">
                    @Html.LabelFor(model => model.ExceptionIndicator, htmlAttributes: new { @class = "control-label col-md-2" })
                </div> <div class="col-md-10">
                    @Html.EditorFor(model => model.ExceptionIndicator, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.ExceptionIndicator, "", new { @class = "text-danger" })
                </div>
            </div>
            <hr />
            <div class="form-group">
                <div class="item-lable">
                    @Html.LabelFor(model => model.ExceptionDate, htmlAttributes: new { @class = "control-label col-md-2" })
                </div> <div class="col-md-10">
                    @Html.EditorFor(model => model.ExceptionDate, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.ExceptionDate, "", new { @class = "text-danger" })
                </div>
            </div>
            <hr />
            <div class="form-group">
                <div class="item-lable">
                    @Html.LabelFor(model => model.ExceptionRemarks, htmlAttributes: new { @class = "control-label col-md-2" })
                </div><div class="col-md-10">
                    @Html.EditorFor(model => model.ExceptionRemarks, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.ExceptionRemarks, "", new { @class = "text-danger" })
                </div>
            </div>
            <hr />
            
            <div class="form-group">
                <div class="item-lable">
                    @Html.LabelFor(model => model.DelayReason, htmlAttributes: new { @class = "control-label col-md-2" })
                </div>  <div class="col-md-10">
                    @Html.EditorFor(model => model.DelayReason, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.DelayReason, "", new { @class = "text-danger" })
                </div>
            </div>
            <hr />
            <div class="form-group">
                <div class="item-lable">
                    @Html.LabelFor(model => model.DelayReasonHistory, htmlAttributes: new { @class = "control-label col-md-2" })
                </div>    <div class="col-md-10">
                    @Html.EditorFor(model => model.DelayReasonHistory, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.DelayReasonHistory, "", new { @class = "text-danger" })
                </div>
            </div>
            <hr />
            <div class="form-group">
                <div class="item-lable">
                    @Html.LabelFor(model => model.Comments, htmlAttributes: new { @class = "control-label col-md-2" })
                </div>  <div class="col-md-10">
                    @Html.EditorFor(model => model.Comments, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Comments, "", new { @class = "text-danger" })
                </div>
            </div>
            <hr />
           
           
        </div>
        
            <div class="tabs-action-button">
                <input type="submit" value="Save" class="footer-button" id="cp-details-cancel"/>
                <input type="button" value="Cancel" class="footer-button" id="cp-details-cancel"/>
               
                <input type="button" value="Exit" class="footer-button exit-popup-btn"  />
            </div>
       
}

<script>
    var error=@(ViewBag.SavingError)
    $(document).ready(function (){
        if(!(error))
            alert("oops, error occurred in saving data process.", error);
    });
</script>

@*<div class="tabs-action-button">but
    <input type="button" value="Save" class="footer-button" id="cp-details-Edit" />
    <input type="button" value="Cancel" class="footer-button" id="cp-details-cancel" />
    <input type="button" value="View" class="footer-button" id="cp-details-view" />
</div>*@
@*<div>
    @Html.ActionLink("Back to List", "Index")
</div>*@

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

PREP/Views/Releases/_ReleaseTabs.cshtml
@model PREP.Models.ReleaseTabs
@{ var Template = ViewBag.Mode != "VIEW" ? "Edit" : "";
    var CurrentTab = Request.QueryString["TabIndex"];}
@{
    bool IsEdited = Request.Path.ToUpper().Contains("EDIT");
    bool IsAdded = Request.Path.ToUpper().Contains("ADD");
}
<div id="tabs">
    <div class="navigation-bar">
        <ul class="main-nav nav navbar-nav" data-tabs="tabs">
            <li data-valid="" class="@( CurrentTab=="0"|| CurrentTab==null ?"active":"")">
                <div class="tab-img sprite GeneralDetails"></div>
                <a class="tab-name" data-toggle="tab" href="#GeneralDetails">General Details</a>
                <div class="tab-status sprite ok"></div>
            </li>
            <li data-valid="" class="@( CurrentTab=="1"?"active":"")">
                <div class="tab-img sprite  ProductsInScope"></div>
                <a class="tab-name" data-toggle="tab" href="#ProductsInScope">Products In Scope</a>
                <div class="tab-status sprite ok"></div>
            </li>
            <li data-valid="" class="@( CurrentTab=="2" ?"active":"")">
                <div class="tab-img sprite  ReleaseCharacteristics"></div>
                <a class="tab-name" data-toggle="tab" href="#ReleaseCharacteristics">Release Characteristics</a>
                <div class="tab-status sprite ok"></div>
            </li>
            <li data-valid="" class="@( CurrentTab=="3"?"active":"")">
                <div class="tab-img sprite  CheckPointReviewMode"></div>
                <a class="tab-name" data-toggle="tab" href="#CheckPointReviewMode">Check Point Review Mode</a>
                <div class="tab-status sprite ok"></div>
            </li>
            <li data-valid="" class="@( CurrentTab=="4" ?"active":"")">
                <div class="tab-img sprite  ReleaseMilestones"></div>
                <a class="tab-name" data-toggle="tab" href="#ReleaseMilestones">Release Milestones</a>
                <div class="tab-status sprite ok"></div>
            </li>
            <li data-valid="" class="@( CurrentTab=="5" ?"active":"")">
                <div class="tab-img sprite  ReleaseStakeholders"></div>
                <a class="tab-name" data-toggle="tab" href="#ReleaseStakeholders">Release Stakeholders</a>
                <div class="tab-status sprite ok"></div>
            </li>
            <li data-valid="" class="@( CurrentTab=="6" ?"active":"")">
                <div class="tab-img sprite AreaOwners"></div>
                <a class="tab-name" data-toggle="tab" href="#AreaOwners">Area Owners</a>
                <div class="tab-status sprite ok"></div>
            </li>
            <li data-valid="" class="@( CurrentTab=="7" ?"active":"")">
                <div class="tab-img sprite  VendorFocalPoints"></div>
                <a class="tab-name" data-toggle="tab" href="#VendorFocalPoints">Vendor Focal Points</a>
                <div class="tab-status sprite ok"></div>
            </li>
            <li class="hide">
                <img src="~/Content/Images/ErrStatus.png" class="tab-status" />
                <span class="tab-mandatory">Mandatory Fields</span>
            </li>
        </ul>
    </div>
    @using (Html.BeginForm("SaveRelease", "Releases", FormMethod.Post, new { @class = "form-tab" ,@id="formsave" }))
    {
        <div class="tab-content" id="tab-content" data-mode="@ViewBag.Mode" data-currentindex="@ViewBag.CurrentTabIndex">

           
            <div id="GeneralDetails" class='tab-pane  @( CurrentTab=="0" || CurrentTab== null? "active" : "" )'>
                @Html.EditorFor(m => m.GeneralDetails, Template + "GeneralDetails")
            </div>
            <div id="ProductsInScope" class='tab-pane  @( CurrentTab=="1"?"active":"")'>
                @*@Html.RenderPartial("EditReleaseCharacteristics", model: Model.ProductsInScope);*@
                @Html.EditorFor(m => m.ProductsInScope, Template + "ProductsInScope")
            </div>
            <div id="ReleaseCharacteristics" class='tab-pane @( CurrentTab=="2"?"active":"")'>
                @Html.EditorFor(m => m.ReleaseCharacteristic, Template + "ReleaseCharacteristicVM")
            </div>
            <div id="CheckPointReviewMode" class='tab-pane @( CurrentTab=="3"?"active":"")'>
                @Html.EditorFor(m => m.CheckPointReviewMode, Template + "CheckPointReviewMode")
            </div>
            <div id="ReleaseMilestones" class='tab-pane  @( CurrentTab=="4"?"active":"")'>
                @*@Html.EditorFor(model => Model.ReleaseMilestones)*@
                @Html.EditorFor(m => m.ReleaseMilestones, Template + "ReleaseMilestones")
            </div>
            <div id="ReleaseStakeholders" class='tab-pane @( CurrentTab=="5"?"active":"")'>
                @Html.EditorFor(m => m.ReleaseStakeholders, Template + "ReleaseStakeholders")
            </div>
            <div id="AreaOwners" class='tab-pane @( CurrentTab=="6"?"active":"")'>
                @Html.EditorFor(m => m.AreaOwners, Template + "AreaOwners")
            </div>
            <div id="VendorFocalPoints" class='tab-pane @( CurrentTab=="7"?"active":"")'>
                @Html.EditorFor(m => m.VendorFocalPoints, Template + "VendorFocalPoints")
            </div>

            <hr class="special-hr" />
            <footer>
                <div class="tabs-action-button">
                    <input type="button" value="Cancel" class="footer-button" id="details-cancel" style=@(IsEdited!=true && IsAdded !=true? "display:none" : "") />
                    <input type="button" value="Save" class="footer-button" id="details-save" style=@(IsEdited!=true && IsAdded !=true? "display:none" : "") />
                    <input type="button" value="< Back" class="footer-button footer-button-nevigate" id="details-prev" />
                    <input type="button" value="Next >" class="footer-button footer-button-nevigate" id="details-next" />
                </div>
            </footer>

        </div>
    }
</div>




@Html.Partial("_EmployeeSearchPartial")



@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/EmployeeSearch")
}