PREP/Controllers/CheckListController.cs
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using PREP.DAL.Functions.Extensions;
using PREP.DAL.Models;
using PREP.DAL.Repositories;
using PREP.DAL.Repositories.Memory;
using PREP.DAL.TableViews;
using PREP.Functions;
using PREP.Models;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Security.Principal;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using System.Web.Script.Serialization;

namespace PREP.Controllers
{
    public class CheckListController : BaseController
    {
        // GET: CheckList
      
        public ActionResult Index()
        {

            return View();
        }
        //[Route("ReleaseCheckList/{ReleaseID}")]
      
        public ActionResult ViewCheckList(int ReleaseID)
        {
            CheckListVM checkListVM = new CheckListVM();
            ViewBag.includeBootsrap = false;
            checkListVM.ReleaseID = ReleaseID;

            //for rout config navigationBreadCrums
            NavigationBreadCrums.SetSesionReleaseID(ReleaseID);

            using (IEmployeeRepository db = new EmployeeRepository())
            {
                checkListVM.UserID = db.GetEmployee(User.Identity.Name);
            }
            //using (IAreaRepository db = new AreaRepository())
            //{
            //    checkListVM.AreaList = db.GetAll();
            //}

            checkListVM.Responsibility = JsonConvert.SerializeObject(
                    Enum.GetValues(typeof(Responsibility))
                    .Cast<Responsibility>().ToDictionary(t => ((int)t).ToString(), t => Enum.GetName(typeof(Responsibility), (int)t)), new KeyValuePairConverter());

            var RiskLevels = Enum.GetValues(typeof(RiskLevels))
                .Cast<RiskLevels>().ToDictionary(t => (int)t, t => EnumExtentions<RiskLevels>.GetDisplayValue(t));

            ViewBag.RiskLevel = RiskLevels;

           checkListVM.RiskLevelList =JsonConvert.SerializeObject(RiskLevels, new KeyValuePairConverter());
            return View(checkListVM);
        }

        [HttpPost]
        public JsonResult getSubAreaListByAreaID(int areaId)
        {
            // var y = convertValue("0", "Responsibility");
            IEnumerable<SubArea> list;
            using (ISubAreaRepository db = new SubAreaRepository())
            {
                list = db.getSubAreaByAreaId(areaId);
            }
            return Json(list);
        }
        //[HttpPost]
        //public DateTime? GetStartHandlingDateCalculate(int releaseId, int questionId)
        //{
        //    using (IQuestionRepository db = new QuestionRepository())
        //    {
        //        return db.HandlingStartDatecalculation(questionId, releaseId);
        //    }
        //}
        [HttpPost]
        public object GetActivityLogByReleaseCheckListId(int releaseChecklistAnswer)
        {
            IEnumerable<History> list;
            using (IHistoryRepository db = new HistoryRepository())
            {
                list = db.GetHistoryReleaseCheckListId(releaseChecklistAnswer);
            }
            string s = "";
            string changeBy;
            foreach (History item in list)
            {
                PREP.DAL.Models.Employee employee = item.ActivityLog.Employee;
                changeBy = employee.FirstName.ToLower() == "system" ? " was changed by the system" : " was changed by " + employee.FirstName + " " + employee.LastName;
                s += getFieldName(item.FieldName) + changeBy + " From " +
                      convertValue(item.OldValue, item.FieldName) +
                        " to " + convertValue(item.NewValue, item.FieldName) + " on " + item.ActivityLog.Date + ". <br/>" + Environment.NewLine;
            }
            return s;
        }

        private string convertValue(string value, string fieldName)
        {
            if (value == String.Empty)
                return "null";

            //GetWhere
            if (fieldName == "AreaID")
                using (IAreaRepository db = new AreaRepository())
                {
                    return db.Find(Int32.Parse(value)).Name;
                }
            if (fieldName == "SubAreaID")
                using (ISubAreaRepository db = new SubAreaRepository())
                {
                    return db.Find(Int32.Parse(value)).Name;
                }
            if (fieldName == "QuestionOwner")
                using (IEmployeeRepository db = new EmployeeRepository())
                {
                    DAL.Models.Employee emp = db.Find(Int32.Parse(value));
                    return emp.FirstName + " " + emp.LastName;
                }
            if (fieldName == "RiskLevelID")
              //  return EnumExtentions<RiskLevels>.GetDisplayValue(value);
               return EnumExtentions<RiskLevels>.GetDisplayValue((RiskLevels)Int32.Parse(value));

            if (fieldName == "Responsibility")
                return Enum.GetName(typeof(Responsibility), Int32.Parse(value));

            return value;
        }


        private string getFieldName(string fieldName)
        {
            switch (fieldName)
            {
                case "RiskLevelID": return "Risk Level";
                case "AreaID": return "Area";
                case "SubAreaID": return "Sub Area";
                case "QuestionText": return "Question Text";
                case "ActualComplation": return "Actual Complation";
                case "HandlingStartDate": return "Handling Start Date";
                case "QuestionOwner": return "Question Owner";
                default: return fieldName;
            }
        }
        public PartialViewResult ViewFilter()
        {
            return PartialView();
        }
        [HttpPost]
        public JsonResult GetCheckList(int ReleaseID)
        {
           
            using (IReleaseChecklistAnswerRepository db = new ReleaseChecklistAnswerRepository())
            {
                return Json(db.GetByFiltering(ReleaseID).ToList());
                // while (List.Count < 300) List.AddRange(List);
            }

           // return Json(List);
        }

        [HttpPost]
        public async Task<int> SaveCheckList(List<ReleaseChecklistAnswerView> Checklist)
        {
            var count = 0;
            if (Checklist != null)
            {
                using (IReleaseChecklistAnswerRepository db = new ReleaseChecklistAnswerRepository())
                {
                    count = await db.EditReleaseChecklist(Checklist, (WindowsPrincipal)User);
                    // while (List.Count < 300) List.AddRange(List);
                }
            }
            return count;
        }
    }
}

PREP/Controllers/StatusController.cs
using PREP.DAL.Repositories;
using PREP.DAL.Repositories.Memory;
using PREP.DAL.Models;
using PREP.DAL.TableViews;
using PREP.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Threading.Tasks;
using System.Security.Principal;
using System.Data.Entity;
using PREP.Functions;
using System.Net.Mail;
using System.Net.Mime;
using System.Web.UI.WebControls;
using System.IO;
using Outlook = Microsoft.Office.Interop.Outlook;
using System.Diagnostics;
using System.Reflection;
using System.Text.RegularExpressions;
using System.Configuration;

namespace PREP.Controllers
{

    public class StatusController : BaseController
    {
        #region Actions
        StatusVM status = new StatusVM();
        List<ScoreIndicator> IndicatorList = new List<ScoreIndicator>()
            {
                new ScoreIndicator() {Min = -1,   Max = 0, ScoreLevel = 0, ScoreIMG = ScoreIMG.blank },
                new ScoreIndicator() {Min = 0, Max = 70,  ScoreLevel = 1, ScoreIMG = ScoreIMG.stop },
                new ScoreIndicator() {Min = 70,  Max = 90,  ScoreLevel = 2, ScoreIMG = ScoreIMG.flag },
                new ScoreIndicator() {Min = 90,  Max = 101, ScoreLevel = 3, ScoreIMG = ScoreIMG.like }

            };

        public ActionResult ViewStatus(int ReleaseId, int CPID = 0, bool IsDraft = true)
        {

            using (ReleaseCPRepository db = new ReleaseCPRepository())
            {
                status = new StatusVM();
                status.ReleaseID = ReleaseId;

                NavigationBreadCrums.SetSesionReleaseID(ReleaseId);

                List<StatusAreaText> statusAreaTexts;
                using (IStatusAreaTextRepository dbStatusAreaText = new StatusAreaTextRepository())
                {
                    statusAreaTexts = dbStatusAreaText.Where(a => a.ReleaseID == ReleaseId).ToList();
                }
                using (IStatusTextRepository dbStatusText = new StatusTextRepository())
                {
                    StatusText statusText = dbStatusText.Where(a => a.ReleaseID == ReleaseId).FirstOrDefault();
                    if (statusText != null)
                        status.StatusText = new StatusTextVM() { ReleaseID = statusText.ReleaseID, HighLightText = statusText.HighLightText };
                }
                using (IReleaseChecklistAnswerRepository dbChecklist = new ReleaseChecklistAnswerRepository())
                {
                    status.AreaScores = dbChecklist.GetStatus(ReleaseId).Select(q =>
                        new AreaScoreVM()
                        {
                            AreaID = q.Area.AreaID,
                            ReleaseID = ReleaseId,
                            Name = q.Area.Name,
                            Score = q.Score,
                            ScoreStatus = IndicatorList.First(i => q.Score >= i.Min && q.Score < i.Max).ScoreIMG,
                            Trand = q.LastScore != null ? TrandCalculation(q.Score, (double)q.LastScore) : Trand.none,
                            StatusAreaText = statusAreaTexts != null && statusAreaTexts.Where(s => s.AreaID == q.Area.AreaID).FirstOrDefault() != null ? statusAreaTexts.Where(s => s.AreaID == q.Area.AreaID).FirstOrDefault().AreaText : "",
                            SubAreaScors = q.SubAreaScores.Select(s =>
                            new SubAreaScoreVM()
                            {
                                Name = s.SubArea.Name,
                                Score = s.Score,
                                ScoreStatus = IndicatorList.First(i => s.Score >= i.Min && s.Score < i.Max).ScoreIMG,
                                SubAreaID = s.SubArea.SubAreaID,
                                Trand = s.LastScore != null ? TrandCalculation(s.Score, (double)s.LastScore) : Trand.none,
                            }).ToList()
                        }).ToList();
                }

            }
            status.Details = new ReleaseGeneralDetails() { ReleaseID = ReleaseId };
            status.CPID = CPID;
            status.IsDraft = IsDraft;
            return View(status);
        }

        private Trand TrandCalculation(double Score, double LastScore)
        {
            var ScoreLevel = IndicatorList.First(i => Score >= i.Min && Score < i.Max).ScoreLevel;
            var LastScoreLevel = IndicatorList.First(i => LastScore >= i.Min && LastScore < i.Max).ScoreLevel;
            Trand newTrand = ScoreLevel == 0 && LastScoreLevel == 0 ? Trand.none : ScoreLevel > LastScoreLevel ? Trand.up : ScoreLevel < LastScoreLevel ? Trand.down : Trand.nochange;
            return newTrand;
        }


        public PartialViewResult _ViewStatusHeader(int releaseId)
        {//need to delete this view from releases
            using (ReleaseProductRepository db = new ReleaseProductRepository())
            {
                ViewBag.productsName = db.GetAllFamilyProductsNamesByRealeaseId(releaseId);
            }
            using (ReleaseRepository db = new ReleaseRepository())
            {
                var release = db.GetReleseForStatus(releaseId);
                status.Details = new ReleaseGeneralDetails();
                status.Details.AccountName = release.Account.Name;
                status.Details.Name = release.Name;
                status.Details.Size = release.Size;
                status.Details.LOB = release.LOB;
                status.Details.ReleaseID = release.ReleaseID;
            }
            return PartialView(status.Details);
        }
        //[HttpGet]
        //public PartialViewResult _HighLightText(int ReleaseId = 19)
        //{
        //    //need to send the currentstatustext for releaseid
        //    //using (StatusTextRepository db = new StatusTextRepository())
        //    //{
        //    //    var statusText = db.FindBy(a => a.ReleaseID == releaseId).FirstOrDefault();
        //    //    if (statusText != null)
        //    //    {
        //    //        status.StatusText = new StatusTextVM();
        //    //        //status.StatusText.HighLightText = statusText.HighLightText;ask if need
        //    //        status.StatusText.ReleaseID = statusText.ReleaseID;
        //    //    }
        //    //}
        //    status.StatusText = new StatusTextVM() { ReleaseID = ReleaseId };

        //    return PartialView(status.StatusText);
        //}

        public PartialViewResult _ReleaseStakeholders(int ReleaseId = 19)
        {
            int count = 8;
            using (ReleaseStakeholderRepository db = new ReleaseStakeholderRepository())
            {
                List<ReleaseStakeholder> releaseStakeholder = db.Where(a => a.ReleaseID == ReleaseId).Include(a => a.Stakeholder).Include(a => a.Employee1).OrderBy(a => a.Stakeholder.Order).Take(count).ToList();
                //List<ReleaseStakeholder> releaseStakeholder = db.FindBy(a => a.ReleaseID == ReleaseId).OrderBy(a=>a.Stakeholder.Order).Take(count).ToList();
                //foreach (var item in releaseStakeholder)
                //{
                //    using (EmployeeRepository emp = new EmployeeRepository())
                //    {
                //        using (StakeholderRepository sh = new StakeholderRepository())
                //        {
                //            DAL.Models.Employee employee1 = emp.Find(item.EmployeeID1);
                //            Stakeholder stakeholder = sh.Find(item.StakeholderID);
                //            ReleaseStakeholderVM rs = new ReleaseStakeholderVM() { ReleaseID = item.ReleaseID, FullNameEmployee1 = employee1 != null ? employee1.FirstName + " " + employee1.LastName : " ", StakeholderName = stakeholder.Name };
                //            status.ReleaseStakeholder.Add(rs);
                //        }
                //    }
                //}
                status.ReleaseStakeholder = new List<ReleaseStakeholderVM>();
                foreach (var item in releaseStakeholder)
                {
                    ReleaseStakeholderVM rs = new ReleaseStakeholderVM() { ReleaseID = item.ReleaseID, FullNameEmployee1 = item.Employee1 != null ? item.Employee1.FirstName + " " + item.Employee1.LastName : " ", StakeholderName = item.Stakeholder != null ? item.Stakeholder.Name : "" };
                    status.ReleaseStakeholder.Add(rs);
                }
            }
            return PartialView(status.ReleaseStakeholder);
        }
        #endregion
        public async Task<int> SaveStatus(StatusVM status)
        {
            try
            {

                int count = 0;
                StatusText statusText;
                using (IStatusTextRepository db = new StatusTextRepository())
                {
                    statusText = db.Where(a => a.ReleaseID == status.StatusText.ReleaseID).FirstOrDefault();
                    if (statusText != null)//edit
                    {
                        if (statusText.HighLightText != status.StatusText.HighLightText)
                        {
                            statusText.HighLightText = status.StatusText.HighLightText;
                            db.Edit(statusText);
                            count += await db.SaveAsync((WindowsPrincipal)User);
                        }
                    }
                    else//create
                    {
                        statusText = new StatusText();
                        statusText.ReleaseID = status.StatusText.ReleaseID;
                        statusText.HighLightText = status.StatusText.HighLightText;
                        db.Add(statusText);
                        count += await db.SaveAsync((WindowsPrincipal)User);
                    }
                }
                if (status.AreaScores != null)
                {
                    using (IStatusAreaTextRepository db = new StatusAreaTextRepository())
                    {

                        status.AreaScores.ForEach(s =>
                        {

PREP/Views/CheckList/ViewCheckList.cshtml
@model PREP.Models.CheckListVM
@{

    ViewBag.Title = "ViewCheckList";
}

<style>
    .actualComplationBtn {
        border-right-width: 1px !important;
        border-left-width: 1px !important;
        border-bottom-width: 2px !important;
        border-top-width: 2px !important;
        margin-left: 0px !important;
    }

    .selected-btn {
        color: #00bbbb !important;
        /*font-weight: bolder !important;*/
        /* background-color: white; */
        border-color: #00bbbb !important;
    }
</style>

@section scripts{
    <script src="~/Scripts/CheckList/bootstrap.min.js"></script>
    <script src="~/Scripts/CheckList/moment.min.js"></script>

    <link rel="stylesheet" href="~/Content/CheckList/bootstrap.min.css">
    <link rel="stylesheet" href="~/Content/CheckList/bootstrap-chosen.css" />

    <link rel="stylesheet" type="text/css" href="~/Content/CheckList/fonts/stylesheet.css">
    <script src="~/Scripts/jquery.loadTemplate-1.4.4.min.js"></script>
    <script src="~/Scripts/jquery.tmpl.min.js"></script>
    <script src="~/Scripts/jquery.tmplPlus.min.js"></script>
    <script src="~/Scripts/CheckList/CheckList.js"></script>
    <script src="~/Scripts/DataTable.js"></script>
    <script src="~/Scripts/jquery-ui-1.10.4.js"></script>
    <script src="~/Scripts/jquery-ui-1.10.4.min.js"></script>
    <link href="~/Content/CheckList/loading.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/Content/CheckList/style.css">
    <script>
        var ReleaseID = @Model.ReleaseID;

        $(document).ready(function (e) {
            $('#loading').removeClass('hide');
           $(".leave-scenario").click(leaveScreen);
            defaultLeaveScenario();
            $.ajax({
                url:  "@Url.Action("GetCheckList")" ,
                type: 'Post',
                data:{ReleaseID:ReleaseID},
                dataType: 'json',
                async: true,
                success: function (data) {
                    //initial checkListRecords Options
                    checklistObj= new checklistRecords(
                                    {
                                        JsonRecords:  data,
                                        Record:{//recorrd params  ReleaseChecklistAnswerView Names
                                            key:"ReleaseChecklistAnswerID",
                                            RiskLevelID: "RiskLevelID",
                                            HandlingStartDate: "HandlingStartDate",
                                            Comments: "Comments",
                                            AreaID:"AreaID",
                                            AreaName:"AreaName",
                                            SubAreaID:"SubAreaID",
                                            SubAreaName:"SubAreaName",
                                            Responsibility:"Responsibility",
                                            QuestionOwnerID: "QuestionOwnerID",
                                            QuestionOwnerName:"QuestionOwnerName",
                                            ActualComplation:"ActualComplation",
                                            LastAutomaticUpdateDate:"LastAutomaticUpdateDate",
                                            LastModifiedDate:"LastModifiedDate"
                                        },
                                        SaveUrl: "@Url.Action("SaveCheckList")",
                                        UserID: @Model.UserID,
                                        ViewUrl: "@Html.Raw(Url.Action("Details", "Releases") + "/View/" + Model.ReleaseID)"
                                    });
                   $('#loading').addClass('hide');
                }
            });
        });
        function Viewchecklist() {
            window.location.href = ROOT + '@Url.Action("ViewCheckList")' ;
        }
        function ViewStatus() {
            leaveScreenForScreen(ROOT + '@Url.Action("ViewStatus", "Status")' ,"Do you want to save your changes before viewing Status?" )
        }
        function AppendRecord(record) {
            $(".questions-container").append($("#template").tmpl(
                                 { "model": record,
                                     "riskLevelList":@Html.Raw(Model.RiskLevelList),
                                     "responsibility":@Html.Raw(Model.Responsibility)}
                                 ));
        }
    </script>
}



@{Html.RenderPartial("_TemplateRecord"); }



<!-- main container starts here -->
<div class="container-fluid checklist">
    <div class="_table_container2 col-lg-12 _padding_left_0">
        <!-- Buttons Starts -->
        <ol class="breadcrumb _breadcrumb _btns _padding_left_0">
            <li class="status_buttons current">
                <button type="button" class="btn btn-info _no-border-radius-btn" disabled onclick="Viewchecklist()">View Checklist</button>
            </li>
            <li class="status_buttons">
                <button type="button" class="btn btn-info _no-border-radius-btn" onclick="ViewStatus()">View Status</button>
            </li>
        </ol>
        <!-- Buttons Ends -->
    </div>
    <div class="table-responsive col-lg-12 _table_container _padding_left_0 _padding_right_0">

        <!-- Questions dropdown tab Starts -->
        <div class="col-lg-12 col-md-12 col-xs-12 _pad_lr_0 _pad_tb_10">
            <div class="col-lg-3 col-md-3 col-xs-3 _padding_right_0" align="left">
                <label for="view" class="_label right">View:&nbsp;&nbsp;&nbsp;&nbsp;</label>
                <!-- Questions dropdown Starts -->
                <select class="form-control width-sm-60 width-auto _top ChecklistFilter" id="ChecklistFilter" name="ChecklistFilter" onload='this.value=1;'>
                    <option  value="0">All Questions</option>
                    <option selected="selected"   value="1">My Pending Questions</option>
                    <option value="2">New Effective Questions</option>
                    <option value="3">Reinitiated Questions</option>
                    <option value="4">Automatic Changed To Low</option>
                    <option value="5">Effective Questions</option>
                </select>
                <!-- Questions dropdown Ends-->
            </div>
            <div class="_sort_by">
                <label for="view" class="_label" style="padding-left:0px;">Sort By:&nbsp;</label>
                <div class="form-group">
                    <!--sort by value
                        value is property of List records
                        atribute type
                        string ="string"
                        number: "number"
                        date:   "date"
                        enum : "enum" , Note: add in ~/scripts/checklist/checklist.js  this.enums
                    -->
                    <select class="form-control width-sm-35 width-auto pull-left  _top" id="SortBy">
                        <option value="QuestionCode" type="string">Question ID</option>
                        <option value="AreaName">Area</option>
                        <option value="SubAreaName">Sub Area</option>
                        <option value="QuestionMilestoneName">Milestone</option>
                        <option value="HandlingStartDate" type="date">Handling Start Date</option>
                        <option value="ActualComplation" type="number">Actual Completion</option>
                        <option value="RiskLevelID" type="enum">Risk level</option>
                        <option value="ExtrenalFocalPoint">External Focal point</option>
                        <option value="Responsibility" type="enum">Responsibility</option>
                        <option value="QuestionOwnerName">Question Owner</option>
                    </select>

                    <button type="button" data-toggle="modal" data-target="#FilterModal" id="Filter" class="btn btn-info _filter">
                        <img src="~/Content/CheckList/icons/filterV.png" class="_filterV">
                        <img src="~/Content/CheckList/icons/filter.png" width="12" height="13">
                        &nbsp;Filters
                    </button>
                </div>
            </div>
            <div class="_btn_group">
                <button type="button" class="view_btn btn btn-info _no-border-radius-btn _transparent_btns" id="Cancel">Cancel</button>
                <button type="button" class="view_btn btn btn-info _no-border-radius-btn _transparent_btns" id="Export">Export to Excel</button>
                <button type="button" class="view_btn btn btn-info _no-border-radius-btn _transparent_btns" id="Save">Save</button>
            </div>
        </div>
        <div class="form-group _pad_r_5">
        </div>
        @*Summary Line*@
        <div class="col-lg-12 col-md-12 col-xs-12 _stats _pad_lr _pad_tb_10" id="divTotal">
            <div class="col-lg-12 col-md-12 col-xs-12 _first-div">
                <div>TOTAL: <b id="total"></b></div>
                <div>Show Stopper: <b id="showStopper"></b></div>
                <div>High: <b id="high"></b></div>
                <div>Medium: <b id="medium"></b></div>
                <div>Low: <b id="low"></b></div>
                <div>None (As Planned): <b id="noneAsPlanned"></b></div>
                <div>None (Closed): <b id="NoneClosed"></b></div>
                <div>Other: <b id="other"></b></div>
            </div>
        </div>
        <div class="col-lg-12 col-md-12 col-xs-12 _pad_lr _pad_tb_10 table" id="table">

            <div class="col-lg-12 col-md-12 col-xs-12 _row-heading_">
                <ul class="_row-heading">
                    <li class="width-9"><div class="col-lg-12">&nbsp;ID</div></li>
                    <li class="_width_Qtxt"><div class="col-lg-12 _padding-0" ><img src="/Content/CheckList/icons/Question_Text_icon.png">&nbsp;Question Text</div></li>
                    <li class="_width_risk_level"><div class="col-lg-12 col-md-12 col-xs-12 _padding-0"><img src="/Content/CheckList/icons/Actual_Completion_icon.png">&nbsp;Actual Completion &amp; Risk Level</div></li>
                    <!--<td colspan="1" class="width-11-1024"><div class="col-lg-12 col-md-12 col-xs-12"><img src="css/icons/Risk_Level_icon.png">&nbsp;Risk Level</div></td>-->
                    <li class="width-35 _comment"><div class="col-lg-12 col-md-12 col-xs-12 _padding-0"><img src="/Content/CheckList/icons/Comments_icon.png">&nbsp;Comments</div></li>
                </ul>
            </div>
            @*<div class="cssload-thecube hide" id="loading">
                <div class="cssload-cube cssload-c1"></div>
                <div class="cssload-cube cssload-c2"></div>
                <div class="cssload-cube cssload-c4"></div>
                <div class="cssload-cube cssload-c3"></div>
            </div>*@
            <div class="cssload-container" id="loading">
                <div class="cssload-whirlpool"></div>
            </div>
            <div class="_repeating_rows_ questions-container">


            </div>
        </div>

    </div>
</div>

<!-- Questions dropdown tab Ends -->

@{Html.RenderPartial("_FilterModal"); }

@Html.Partial("_EmployeeSearchPartial")